name: linter

on:
  # Execute on every push to any branch
  push:
    branches:
      - "**"


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
      - run: npm install -g dockerfilelint prettier@2.3.0
      - run: dockerfilelint Dockerfile
      - run: prettier --check "**/*.md"
